In [1]:
import numpy as np

In [2]:
#1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
arr = np.arange(6)

In [3]:
arr

array([0, 1, 2, 3, 4, 5])

In [4]:
#2. Given a NumPy array 'arr', check if its data type is float64.
#    arr = np.array([1.5, 2.6, 3.7])
arr = np.array([1.5, 2.6, 3.7])
arr_datatype = arr.dtype
if arr_datatype == float :
    print('Yes , the Datatype of arr is float in nature')
else :
    print('NO , the Datatype of arr is float in nature')

Yes , the Datatype of arr is float in nature


In [5]:
#3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr = np.array([2+4j , 5+7j , 3+6j], dtype=np.complex128)
print('The array is::', arr)
print('The Datatype of the arr is::',arr.dtype)

The array is:: [2.+4.j 5.+7.j 3.+6.j]
The Datatype of the arr is:: complex128


In [6]:
#4. Convert an existing NumPy array 'arr' of integers to float32 data type.
arr = np.array([2,4,5,8,6])
arr_float = arr.astype(np.float32)
print('The orginal data type is ::', arr.dtype)
print('The converted data type is ::', arr_float.dtype)

The orginal data type is :: int32
The converted data type is :: float32


In [7]:
#5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
arr = np.array([1.2452,2.3654,8.2556,9.5656], dtype = np.float64)
arr_float32 = arr.astype(np.float32)
print('The orginal data type is ::', arr.dtype)
print('The converted data type is ::', arr_float32.dtype)

The orginal data type is :: float64
The converted data type is :: float32


In [ ]:
#6.  Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type
import numpy as np
def array_attributes(arr):
  
    shape = arr.shape
    size = arr.size
    data_type = arr.dtype
    
    return shape, size, data_type

# Example usage:
arr = np.array([[5,6,4,9], [4,2,7,3]])
attributes = array_attributes(arr)
print(f"Shape: {attributes[0]}, Size: {attributes[1]}, Data Type: {attributes[2]}")


In [ ]:
#7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality..

def array_dimension(arr):
    dimension = arr.ndim
    return dimension
# Example ::
arr = np.array([[1,5,4],[8,6,3]])
dimension = array_dimension(arr)
print(f" dimension is : {dimension}")


In [ ]:
#8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total 
#size in bytes..
def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size , total_size

# Example
arr = np.array([[1,2,5],[4,7,6]])
info =  item_size_info(arr)
print(f" Item size is:{info[0]} bytes , Total size is:{info[1]} bytes")


In [ ]:
#9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array..
def array_strides(arr):
    strides = arr.strides
    return strides

# Example
arr = np.array([[1,6,8,5],[4,3,7,6]])
strides = array_strides(arr)
print(f" Strides of the array is: {strides}")


In [ ]:
#10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape 
# and strides of the array.
def shape_stride_relationship(arr):
    shape = arr.shape
    strides = arr.strides
    return shape,strides

# Example
arr = np.array([[1,6,8,5],[4,3,7,6]])
shape_strides = shape_stride_relationship(arr)
print(f" Shape of the array is: {shape_strides[0]} , Strides of the array is: {shape_strides[1]} ")

In [ ]:
#11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements::

import numpy as np

In [ ]:
def create_zeros_array(arr):
    n = int(input('Enter the no. of elements::'))
    arr = np.zeros(n)
    return arr
#Example
arr_zeros = create_zeros_array(arr)
print('A Numpy array of zeros is ::',arr_zeros)

In [ ]:
#12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D 
# NumPy array filled with ones of size `rows x cols`..
def create_ones_matrix(arr):
    rows = int(input('Enter no. of Rows::'))
    cols = int(input('Enter no. of columns::'))
    arr = np.ones((rows,cols))
    return arr
#Example
arr_ones = create_ones_matrix(arr)
print('A Numpy 2D-Array of ones is :',arr_ones)

In [ ]:
#13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and 
# creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified 'step'::

def generate_range_array(arr):
    start = int(input('Enter the starting element'))
    stop = int(input('Enter the ending element'))
    step = int(input('Enter the step size'))
    arr = np.arange(start,stop,step)
    return arr
    
#Example
arr_with_step_size = generate_range_array(arr)
print(f"The Numpy array is :{arr_with_step_size}")

In [ ]:
#14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as 
# arguments and generates a NumPy array with num equally spaced values between `start` and `stop` inclusive).

def generate_linear_space(arr):
    start = float(input('Enter the starting element'))
    stop = float(input('Enter the ending element'))
    num = int(input('Enter the step size'))
    arr = np.linspace(start,stop,num)
    return arr
    
#Example
arr_linear_space = generate_linear_space(arr)
print(f"The Numpy array is :{arr_linear_space}")

In [ ]:
#15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square 
# identity matrix of size `n x n` using `numpy.eye`.
def create_identity_matrix(arr):
    n = int(input('Enter the no.::'))
    return np.eye(n)
#Example
array = create_identity_matrix(arr)
print('The squre identity matrix is::',array)

In [ ]:
#16. Write a function that takes a Python list and converts it into a NumPy array:
def list_into_array(arr):
    list = []
    n = int(input('Enter the no.::'))
    for i in range(n):
        list.append(int(input("Enter the element")))
    return np.array(list)
#Example
array = list_into_array(arr)
print('The Numpy Array is ::',array)
    

In [ ]:
#17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data::

# Step 1: Create an initial NumPy array
original_array = np.array([9,8,3,6,1,4,2,4,5,8,7,9])
view_array = original_array.view()

#disply
print("Original array:", original_array)
print("View array:", view_array)

# Step 2: Modify the view array by reshape::
view_array = original_array.view().reshape(4,3)


# Display 
print("Modified view array:", view_array)

# again modify into 16 bit int ::
view_array_1 = original_array.view(np.int16)

#display
print("modified view array:",view_array_1)

In [ ]:
#18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

def concatenates_arrays(arr1,arr2,axis=0):
    return np.concatenate((arr1,arr2), axis=axis)

#Example
arr1 = np.array([[4,5,8],[5,9,7]])
arr2 = np.array([[5,9,3],[6,4,7]])
output_axis_0 = concatenates_arrays(arr1,arr2,axis=0)
print(output_axis_0)
output_axis_1 = concatenates_arrays(arr1,arr2,axis=1)
print(output_axis_1)

In [ ]:
#19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy concatenate'::

arr1 = np.array([[4,6,7],[6,4,8]])
arr2 = np.array([[2,6],[8,7]])
result = np.concatenate((arr1,arr2), axis=1)
print(result)

In [ ]:
#20. Write a function that vertically stacks multiple NumPy arrays given as a list::

def vertically_stack(array):
    return np.vstack(array)

#Example
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3 = [7,8,9]
result = vertically_stack([arr1,arr2,arr3])
print(result)

In [ ]:
#21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size::

def generate_range_array(arr):
    start = int(input('Enter the starting element'))
    stop = int(input('Enter the ending element'))
    step = int(input('Enter the step size'))
    arr = np.arange(start,stop+1,step)
    return arr
    
#Example
arr_with_step_size = generate_range_array(arr)
print(f"The Numpy array is :{arr_with_step_size}")


In [ ]:
#22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive)::

def generate_linear_space(start,stop,step):
    arr = np.linspace(start,stop,step)
    return arr
    
#Example
arr_linear_space = generate_linear_space(0,1,10)
print(f"The Numpy array is :{arr_linear_space}")


In [ ]:
#23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive)::

def generate_log_space(start,stop,step):
    arr = np.logspace(start,stop,step)
    return arr
    
#Example
arr_log_space = generate_log_space(0,3,5)
print(f"The Numpy array is :{arr_log_space}")


In [ ]:
#24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100::

import pandas as pd
  
array = np.random.randint(1,101, size=(5,3))
df = pd.DataFrame(array, columns=['Column_1', 'Column_2', 'Column_3'])
print(df)
    

    
  


In [ ]:
#25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame::

def negative_values_replace(df,column):
    df[column] = np.where(df[column]<0 , 0 , df[column])
    return df

#Example
data = {'A' : [5,2,-9,-8,6,-7,8],
      'B' : [-3,5,-9,6,8,-7,2]}
df= pd.DataFrame(data)
print(df)
df = negative_values_replace(df,'B')
print('After replacing negative values from the column::')
print(df)

In [ ]:
#26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2]
print(third_element)

In [ ]:
#27. Retrieve the element at index (1, 2) from the 2D NumPy array::
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                   [7, 8, 9]])

element = arr_2d[1, 2]

print("The element at index (1, 2) is:", element)



In [ ]:
#28. Using boolean indexing, extract elements greater than 5 from the given NumPy array:

arr = np.array([3, 8, 2, 10, 5, 7])
greater_than_five = arr[arr > 5]
print(greater_than_five)

In [ ]:
#29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array::

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
sliced_array = arr[2:6]
print(sliced_array)

In [ ]:
#30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array::

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
sub_array = arr_2d[0:2 ,1:3]
print(sub_array)

In [ ]:
#31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array ::

def extract_from_2D_array(arr,indices):
    return np.take(arr,indices)

#Example
arr = np.array([[2,5,8],
               [6,5,3],
               [8,2,3]])
indices = np.array([[0,2] , [1,3]])

result =  extract_from_2D_array(arr,indices)
print(result)

In [ ]:
#32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing:::
def greater_than_threshold(arr,threshold):
    return arr[arr > threshold]

#Example
arr = np.array([2,5,3,10,47,59,2,3])
threshold = 7
result = greater_than_threshold(arr,threshold)
print(result)

In [ ]:
#33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension::

def extracts_from_3d_array(arr, dim_1, dim_2, dim_3):
    first_result = np.take(arr, dim_1, axis = 0)
    next_result = np.take(first_result, dim_2, axis = 1)
    final_result = np.take(next_result, dim_2, axis = 2)
    return final_result

#Example
arr = np.arange(27).reshape(3,3,3)
dim_1 = [2,1,0]
dim_2 = [0,1,2]
dim_3 = [1,2,3]
extract_elements = extracts_from_3d_array(arr, dim_1, dim_2, dim_3)
print(extract_elements)
    

In [ ]:
#34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing::

def boolean_indexing(arr, num_1, num_2):
    return arr[(arr > num_1) & (arr < num_2)]

#Example
arr = np.array([2,5,7,49,6,45,18,2,33,99,84,15])
num_1 = 10
num_2 = 70
final_output = boolean_indexing(arr, num_1, num_2)
print(final_output)
    

In [ ]:
#35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays::
def extracts_elements(arr, row_indices, column_indices):
     row_indices = np.array(row_indices)
     column_indices = np.array(column_indices)
     return arr[row_indices , column_indices]

#Example
arr = np.array([[3,6,8],
                [4,2,5],
                [0,7,9]])
row_indices = [2,0,1]
column_indices = [2,1,0]
final_output = extracts_elements(arr, row_indices, column_indices)
print(final_output)

In [ ]:
#36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

arr = np.arange(9).reshape(3,3)
scalar = 8
broadcast_arr = arr + scalar
print(broadcast_arr)

In [ ]:
#37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.::

arr1 = np.array([[1,2,3]])
arr2 = np.array ([[2,5,8,6],
                 [1,7,4,4],
                 [9,6,3,6]])
result = arr2 * arr1.T
print(result)

In [ ]:
#38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using Numpy broadcasting::
arr1 = np.array([[5,8,6,4]])
arr2 = np.array([[4,5,6],
                [7,9,8],
                [3,5,7],
                [1,5,9]])
result = arr2 + arr1.T
print(result)

In [ ]:
#39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting::

arr1 = np.array([[5],
                [9],
                [7]])
arr2 = np.array([[4,5,6]])
result = arr1 + arr2
print(result)

In [ ]:
#40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility::

arr1 = np.array([[4,5,6],
               [7,5,3]])
arr2 = np.array([[5,8],
                [7,3]])
arr_2 = np.hstack((arr2, arr2[:, :1]))
print(arr_2)
result = arr1* arr_2
print(result)


In [ ]:
#41. Calculate column wise mean for the given array::
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
column_wise_mean = np.mean(arr, axis = 0)
print(column_wise_mean)

In [ ]:
#42. Find maximum value in each row of the given array:

arr = np.array([[1, 2, 3], [4, 5, 6]])
max_num_in_row = np.max(arr, axis = 1)
print(max_num_in_row)

In [ ]:
#43. For the given array, find indices of maximum value in each column::

arr = np.array([[1, 2, 3], [4, 5, 6]])
column_indices_max_num = np.argmax(arr, axis = 0)
print(column_indices_max_num)

In [ ]:
#44. For the given array, apply custom function to calculate moving sum along rows::

arr = np.array([[1, 2, 3], [4, 5, 6]])
moving_sum = np.cumsum(arr, axis= 1)  ##considering window size of 1.
print(moving_sum)


In [ ]:
#45. In the given array, check if all elements in each column are even::

arr = np.array([[2, 4, 6], [3, 15, 7]])
even_check_along_column = np.all(arr%2 == 0, axis =0)
print(even_check_along_column)

In [ ]:
#46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix::

original_array = np.array([1, 2, 3, 4, 5, 6])
m = int(input('Enter the dimension of Row'))
n = int(input('Enter the dimension of Column'))
if original_array.size == m * n:
    reshaping_array = original_array.reshape(m,n)
    print(reshaping_array)
else :
    print('Reshaping not possible')

In [ ]:
#47. Create a function that takes a matrix as input and returns the flattened array::

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

def flattened_array(input_matrix):
    return input_matrix.flatten()

#Example
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flattened_array(input_matrix)
print(flattened_array)

In [ ]:
#48. Write a function that concatenates two given arrays along a specified axis::

array1 = np.array([[1, 2], [3, 4]])

array2 = np.array([[5, 6], [7, 8]])

In [ ]:
def concatenates_arrays(array1, array2, axis = 1):
    return np.concatenate((array1, array2), axis = axis)

#Example
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

result = concatenates_arrays(array1, array2, axis =1)
print(result)

In [ ]:
#49. Create a function that splits an array into multiple sub-arrays along a specified axis:::
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [22]:
def splits_array(original_array, section, axis = 0):
    return np.array_split(original_array, section, axis = axis)

#Example
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = splits_array(original_array, 3, axis = 0)
print(result)
for arr in result:
    print(arr)
    
    
    

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


In [30]:
#50. Write a function that inserts and then deletes elements from a given array at specified indices::

def insert_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    modified_array = np.insert(original_array, indices_to_insert, values_to_insert)
    indices_to_delete = sorted(indices_to_delete)
    for idx in indices_to_delete :
        modified_array = np.delete(modified_array,idx)
        indices_to_delete = [i-1 if i > idx else i for i in indices_to_delete]
    return modified_array

#Example
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
result = insert_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(result)
    

[ 1 10  3 11  5]


In [32]:
#51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

arr1 = np.random.randint(0,10,10)
arr2 = np.arange(1,11)
result = arr1 + arr2
print(arr1)
print(arr2)
print(result)

[1 0 2 7 5 8 4 5 5 6]
[ 1  2  3  4  5  6  7  8  9 10]
[ 2  2  5 11 10 14 11 13 14 16]


In [33]:
#52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract 'arr2' from 'arr1' elementr-wise::

arr1 = np.arange(10,0,-1)
arr2 = np.arange(1,11)
subtract = arr1 - arr2
print(arr1)
print(arr2)
print(subtract)

[10  9  8  7  6  5  4  3  2  1]
[ 1  2  3  4  5  6  7  8  9 10]
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [34]:
#53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.Perform element-wise multiplication between `arr1` and `arr2`. 

arr1 = np.random.randint(1,10,5)
arr2 = np.arange(1,6)
multiplication = arr1 * arr2
print(arr1)
print(arr2)
print(multiplication)

[9 3 9 3 2]
[1 2 3 4 5]
[ 9  6 27 12 10]


In [40]:
#54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`::

arr1 = np.arange(2,11,2)
arr2 = np.arange(1,6)
division = arr1 / arr2
print('arr1:',arr1)
print('arr2:',arr2)
print('Final Result:',division)

arr1: [ 2  4  6  8 10]
arr2: [1 2 3 4 5]
Final Result: [2. 2. 2. 2. 2.]


In [6]:
#55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers 
#    reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise::

arr1 = np.arange(1,6)
arr2 = np.arange(5,0,-1)

print('Array1 is',arr1)
print('Array2 is',arr2)

result = np.power(arr1, arr2)

print('Exponentiation of arr1 is',result)

Array1 is [1 2 3 4 5]
Array2 is [5 4 3 2 1]
Exponentiation of arr1 is [ 1 16 27 16  5]


In [9]:
#56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings::
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [11]:
def count_substring(arr, substring):
    count = 0
    for i in arr:
        count += i.count(substring)
    return count

#Example
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
result = count_substring(arr, substring)
print(f' The substring {substring} occure {result} time in the array.')

 The substring hello occure 3 time in the array.


In [12]:
#57. Write a function that extracts uppercase characters from a NumPy array of strings::
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [12]:
def extracts_uppercase(arr):
    uppercase_char = []
    for i in arr:
        for char in i:
            if char.isupper():
                uppercase_char.append(char)
    return uppercase_char

#Example
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_array = extracts_uppercase(arr)
print(uppercase_array)

['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']


In [13]:
#58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string::
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [22]:
def replace_string(arr,old_substring,new_substring):
    return np.char.replace(arr, old_substring, new_substring)

#Example

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

old_substring = 'grape'
new_substring = 'lichhi'
replace_array = replace_string(arr, old_substring, new_substring)

print(replace_array)

['apple' 'banana' 'lichhi' 'pineapple']


In [26]:
#59. Write a function that concatenates strings in a NumPy array element-wise::
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

In [33]:
def concatenate_array(arr1, arr2):
    return np.concatenate((arr1, arr2))

#Example

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

result = concatenate_array(arr1, arr2)

print(result)

['Hello' 'World' 'Open' 'AI']


In [34]:
#60. Write a function that finds the length of the longest string in a NumPy array::
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [36]:
def longest_string(arr):
    lengths = np.char.str_len(arr)
    max_length = np.max(lengths)
    return max_length

#Example

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

result = longest_string(arr)

print (result)        

9


In [37]:
#61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's function::


In [54]:
arr = np.random.randint(1,1001,100)

mean = np.mean(arr)
median = np.median(arr)
variance =np.var(arr)
standard_daviation = np.std(arr)

print('The Mean of the Array is:',mean)
print('The Median of the Array is:',median)
print('The Variance of the Array is:',variance)
print('The Standard Daviation of the Array is:',standard_daviation)

The Mean of the Array is: 521.95
The Median of the Array is: 528.5
The Variance of the Array is: 83915.4675
The Standard Daviation of the Array is: 289.6816657988558


In [55]:
#62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset::

arr = np.random.randint(1,101,50)

percentile_25th = np.percentile(arr,0.25)
percentile_75th = np.percentile(arr,0.75)

print('The random Array is :',arr)
print('The 25th percentile is :',percentile_25th)
print('The 75th percentile is :',percentile_75th)

The random Array is : [65 55 52 65 83 78 49 10 52  7 96 21 38 82 40 99 41 68 74 13 87 13 77 99
 93 51 24 26 82 16 20 12 44 40 35 21 62 77 58 92 57 75 77 67  3 13 19 58
 98 96]
The 25th percentile is : 3.49
The 75th percentile is : 4.47


In [64]:
#63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function::


arr1 = np.array([13,26,39,52,65])
arr2 = np.array([5, 2, 5, 9, 5])

correlation_matrix = np.corrcoef(arr1, arr2)

correlation_coefficient = correlation_matrix[0, 1]

print("Array 1:", arr1)
print("Array 2:", arr2)
print('The matrix is:',correlation_matrix)
print("Correlation coefficient:", correlation_coefficient)

Array 1: [13 26 39 52 65]
Array 2: [5 2 5 9 5]
The matrix is: [[1.         0.44450044]
 [0.44450044 1.        ]]
Correlation coefficient: 0.44450044450066667


In [8]:
#64. Create two matrices and perform matrix multiplication using NumPy's `dot` function::

arr1 = np.array([[4,8,6],
                [8,9,6],
                [8,2,7]])
arr2 = np.array([[6,5,4],
                [8,9,7],
                [2,4,3]])

result = np.dot(arr1,arr2)

print(result)

[[100 116  90]
 [132 145 113]
 [ 78  86  67]]


In [10]:
#65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles::


arr = np.random.randint(10, 1001, 50)


percentile_10th = np.percentile(arr, 10)
percentile_50th = np.percentile(arr, 50)  
percentile_90th = np.percentile(arr, 90)


first_quartile = np.percentile(arr, 25)
third_quartile = np.percentile(arr, 75)


print(f"Array: {arr}")
print(f"10th percentile: {percentile_10th}")
print(f"50th percentile (median): {percentile_50th}")
print(f"90th percentile: {percentile_90th}")
print(f"First quartile (25th percentile): {first_quartile}")
print(f"Third quartile (75th percentile): {third_quartile}")


Array: [589 835 971 147 118 539 970 982 445 552  48 432 212 544 911 532 641 477
 620  45 885 572 422  33 781 470 806 461 728 971 746  71 615 669 249 278
 712 612 656 264 956 342 551 226 524 703 772 955 246 578]
10th percentile: 144.10000000000002
50th percentile (median): 562.0
90th percentile: 955.1
First quartile (25th percentile): 362.0
Third quartile (75th percentile): 741.5


In [12]:
#66. Create a NumPy array of integers and find the index of a specific element.

arr = np.array([1,2,5,8,7,4,6,3,9])

element = int(input('enter the element 1 to 9 :'))

element_index = np.where(arr == element)[0]

print(f"Array: {arr}")
print(f"Element to find: {element}")
print(f"Index of the element: {element_index}")

enter the element 1 to 9 : 9


Array: [1 2 5 8 7 4 6 3 9]
Element to find: 9
Index of the element: [8]


In [15]:
#67. Generate a random NumPy array and sort it in ascending order::

arr = np.random.randint(1,101,15)

sorting_array = np.sort(arr)

print('The Original Array:',arr)
print('The Sorting Array:',sorting_array)

The Original Array: [47 54 80 33 84 31 77 10 97 30  5 93 80 31 74]
The Sorting Array: [ 5 10 30 31 31 33 47 54 74 77 80 80 84 93 97]


In [16]:
#68. Filter elements >20  in the given NumPy array::
arr = np.array([12, 25, 6, 42, 8, 30])

In [19]:
arr = np.array([12, 25, 6, 42, 8, 30])

filtered_array = arr[arr > 20]

print('Original Array:',arr)
print('Filtered Array :',filtered_array)

Original Array: [12 25  6 42  8 30]
Filtered Array : [25 42 30]


In [20]:
#69. Filter elements which are divisible by 3 from a given NumPy array::
arr = np.array([1, 5, 8, 12, 15])

In [22]:
arr = np.array([1, 5, 8, 12, 15])

filtered_array = arr[arr % 3 == 0]

print('Original Array:',arr)
print('Filtered Array :',filtered_array)

Original Array: [ 1  5  8 12 15]
Filtered Array : [12 15]


In [23]:
#70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array::
arr = np.array([10, 20, 30, 40, 50])

In [25]:
arr = np.array([10, 20, 30, 40, 50])

filtered_array = arr[(arr >= 20) & (arr <= 40)]

print('Original Array:',arr)
print('Filtered Array :',filtered_array)

Original Array: [10 20 30 40 50]
Filtered Array : [20 30 40]


In [26]:
#71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder::
arr = np.array([1, 2, 3])

In [34]:
arr = np.array([1, 2, 3])

byte_order = arr.dtype.byteorder

print('Original Array :',arr)
print('Byte Order :',byte_order)

Original Array : [1 2 3]
Byte Order : =


In [7]:
#72. For the given NumPy array, perform byte swapping in place using `byteswap()`::
arr = np.array([1, 2, 3], dtype=np.int32)

In [8]:
arr = np.array([1, 2, 3], dtype=np.int32)

arr.byteswap('True')

print(arr)

[16777216 33554432 50331648]


In [10]:
#73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`::
arr = np.array([1, 2, 3], dtype=np.int32)

In [14]:
arr = np.array([1, 2, 3], dtype=np.int32)

swaped_array =  arr.newbyteorder()

print('Original Array :',arr)
print('Swaped Array :',swaped_array)

Original Array : [1 2 3]
Swaped Array : [16777216 33554432 50331648]


In [15]:
#74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`::
arr = np.array([1, 2, 3], dtype=np.int32)

In [16]:
#75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`::
arr = np.array([1, 2, 3], dtype=np.int32)

In [17]:
arr = np.array([1, 2, 3], dtype=np.int32)

array_byteorder = arr.dtype.byteorder

native_byteorder = '<' if np.dtype(np.int32).newbyteorder('N').byteorder == '=' else '>'

if array_byteorder in ('=', native_byteorder):
    print("Byte swapping is not necessary.")
else:
    print("Byte swapping is necessary.")

print("Array byte order:", array_byteorder)
print("Native system byte order:", native_byteorder)


Byte swapping is not necessary.
Array byte order: =
Native system byte order: <


In [18]:
#76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`::

In [22]:
arr1 = np.arange(1,11)

copy_arr1 = arr1.copy()

copy_arr1[2] = 75

print('Original Array :',arr1)
print('Copy Array :',copy_arr1)


Original Array : [ 1  2  3  4  5  6  7  8  9 10]
Copy Array : [ 1  2 75  4  5  6  7  8  9 10]


In [23]:
#77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from 
# the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [34]:
matrix = np.random.randint(1, 100, size=(3, 3))

view_slice = matrix[:3, :2] 

view_slice[0, 0] = 712

print("Original matrix after modification:")
print(matrix)

print("View slice after modification:")
print(view_slice)


Original matrix after modification:
[[712  85  28]
 [ 61  29  98]
 [ 43  58  91]]
View slice after modification:
[[712  85]
 [ 61  29]
 [ 43  58]]


In [8]:
#78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice 
# `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`::

In [10]:
array_a = np.arange(1,13).reshape(4,3)
print('The Original Array:')
print(array_a)

view_b = array_a[ : ,1:2]
print('The Slice Array:')
print(view_b)

view_b += 5
print('The Broadcast Array is :')
print(view_b)

print('After altering view_b:')
print(array_a)

The Original Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
The Slice Array:
[[ 2]
 [ 5]
 [ 8]
 [11]]
The Broadcast Array is :
[[ 7]
 [10]
 [13]
 [16]]
After altering view_b:
[[ 1  7  3]
 [ 4 10  6]
 [ 7 13  9]
 [10 16 12]]


In [11]:
#79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view 
#`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it 
#reflects changes in the original `orig_array`::

In [14]:
orig_array = np.arange(1,9).reshape(2,4)
print("Original orig_array:")
print(orig_array)

reshaped_view = orig_array.reshape(4,2)
print("reshaped_view (before modification ) :")
print(reshaped_view)

reshaped_view[2,1] = 43
print("reshaped_view (after modification):")
print(reshaped_view)

print("orig_array after modifying reshaped_view:")
print(orig_array)

Original orig_array:
[[1 2 3 4]
 [5 6 7 8]]
reshaped_view (before modification ) :
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
reshaped_view (after modification):
[[ 1  2]
 [ 3  4]
 [ 5 43]
 [ 7  8]]
orig_array after modifying reshaped_view:
[[ 1  2  3  4]
 [ 5 43  7  8]]


In [15]:
#80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of 
# elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`::

In [27]:
np.random.seed(17)
data = np.random.randint(1,11, size = (3,4))
print("Original data:")
print(data)

data_copy = data[data > 5].copy()
print("data_copy (before modification):")
print(data_copy)

if data_copy.size > 2:
    data_copy[2] = 27
print("data_copy (after modification):")
print(data_copy)

print("data after modifying data_copy:")
print(data)

Original data:
[[ 2  7  7 10]
 [ 1  7  5  8]
 [ 5  8  2  2]]
data_copy (before modification):
[ 7  7 10  7  8  8]
data_copy (after modification):
[ 7  7 27  7  8  8]
data after modifying data_copy:
[[ 2  7  7 10]
 [ 1  7  5  8]
 [ 5  8  2  2]]


In [28]:
#81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them::

In [33]:
A = np.array([[4,5,6],
             [7,8,9],
             [1,5,9]])
B = np.array([[1,2,3],
             [4,2,6],
             [3,5,7]])
print('A matrix :\n',A)
print('B matrix :\n',B)

add = A + B
sub = A - B
print('Addition of two matrix :\n',add)
print('Subtraction of two matrix :\n',sub)

A matrix :
 [[4 5 6]
 [7 8 9]
 [1 5 9]]
B matrix :
 [[1 2 3]
 [4 2 6]
 [3 5 7]]
Addition of two matrix :
 [[ 5  7  9]
 [11 10 15]
 [ 4 10 16]]
Subtraction of two matrix :
 [[ 3  3  3]
 [ 3  6  3]
 [-2  0  2]]


In [34]:
#82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication::

In [35]:
C = np.array([[5,6],
             [8,9],
             [7,3]])
D = np.array([[7,5,1,6],
             [9,2,3,4]])

print('C matrix (3*2) :\n',C)
print('D matrix (2*4) :\n',D)

mul = np.dot(C,D)

print('Multiplication of C and D :\n',mul)

C matrix (3*2) :
 [[5 6]
 [8 9]
 [7 3]]
D matrix (2*4) :
 [[7 5 1 6]
 [9 2 3 4]]
Multiplication of C and D :
 [[ 89  37  23  54]
 [137  58  35  84]
 [ 76  41  16  54]]


In [36]:
#83. Create a matrix `E` and find its transpose::

In [37]:
E = np.array([[1,5,9],
             [7,5,3],
             [6,8,2]])
print('Matrix E :\n',E)

E_transpose = E.T

print('Transpose of matrix of E is :\n',E_transpose)

Matrix E :
 [[1 5 9]
 [7 5 3]
 [6 8 2]]
Transpose of matrix of E is :
 [[1 7 6]
 [5 5 8]
 [9 3 2]]


In [38]:
#84. Generate a square matrix `F` and compute its determinant ::

In [42]:
F = np.array([[4,8,2],
              [6,3,7],
              [5,7,1]])

print('Matrix F :\n',F)

det_F = np.linalg.det(F)

print('Determinant of matrix F:\n',det_F)

Matrix F :
 [[4 8 2]
 [6 3 7]
 [5 7 1]]
Determinant of matrix F:
 102.00000000000004


In [43]:
#85. Create a square matrix `G` and find its inverse::

In [44]:
G = np.array([[8,2],
              [9,1]])

print('Matrix G:\n',G)

G_inverse = np.linalg.inv(G)
print('Inverse of matrix G:\n',G_inverse)

Matrix G:
 [[8 2]
 [9 1]]
Inverse of matrix G:
 [[-0.1  0.2]
 [ 0.9 -0.8]]
