In [6]:
import numpy as np

In [7]:
#1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
arr = np.arange(6)

In [8]:
arr

array([0, 1, 2, 3, 4, 5])

In [9]:
#2. Given a NumPy array 'arr', check if its data type is float64.
#    arr = np.array([1.5, 2.6, 3.7])
arr = np.array([1.5, 2.6, 3.7])
arr_datatype = arr.dtype
if arr_datatype == float :
    print('Yes , the Datatype of arr is float in nature')
else :
    print('NO , the Datatype of arr is float in nature')

Yes , the Datatype of arr is float in nature


In [21]:
#3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr = np.array([2+4j , 5+7j , 3+6j], dtype=np.complex128)
print('The array is::', arr)
print('The Datatype of the arr is::',arr.dtype)

The array is:: [2.+4.j 5.+7.j 3.+6.j]
The Datatype of the arr is:: complex128


In [35]:
#4. Convert an existing NumPy array 'arr' of integers to float32 data type.
arr = np.array([2,4,5,8,6])
arr_float = arr.astype(np.float32)
print('The orginal data type is ::', arr.dtype)
print('The converted data type is ::', arr_float.dtype)

The orginal data type is :: int32
The converted data type is :: float32


In [44]:
#5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
arr = np.array([1.2452,2.3654,8.2556,9.5656], dtype = np.float64)
arr_float32 = arr.astype(np.float32)
print('The orginal data type is ::', arr.dtype)
print('The converted data type is ::', arr_float32.dtype)

The orginal data type is :: float64
The converted data type is :: float32


In [6]:
#6.  Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type
import numpy as np
def array_attributes(arr):
  
    shape = arr.shape
    size = arr.size
    data_type = arr.dtype
    
    return shape, size, data_type

# Example usage:
arr = np.array([[5,6,4,9], [4,2,7,3]])
attributes = array_attributes(arr)
print(f"Shape: {attributes[0]}, Size: {attributes[1]}, Data Type: {attributes[2]}")


Shape: (2, 4), Size: 8, Data Type: int32


In [9]:
#7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality..

def array_dimension(arr):
    dimension = arr.ndim
    return dimension
# Example ::
arr = np.array([[1,5,4],[8,6,3]])
dimension = array_dimension(arr)
print(f" dimension is : {dimension}")


 dimension is : 2


In [14]:
#8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total 
#size in bytes..
def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size , total_size

# Example
arr = np.array([[1,2,5],[4,7,6]])
info =  item_size_info(arr)
print(f" Item size is:{info[0]} bytes , Total size is:{info[1]} bytes")


 Item size is:4 bytes , Total size is:24 bytes


In [17]:
#9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array..
def array_strides(arr):
    strides = arr.strides
    return strides

# Example
arr = np.array([[1,6,8,5],[4,3,7,6]])
strides = array_strides(arr)
print(f" Strides of the array is: {strides}")


 Strides of the array is: (16, 4)


In [18]:
#10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape 
# and strides of the array.
def shape_stride_relationship(arr):
    shape = arr.shape
    strides = arr.strides
    return shape,strides

# Example
arr = np.array([[1,6,8,5],[4,3,7,6]])
shape_strides = shape_stride_relationship(arr)
print(f" Shape of the array is: {shape_strides[0]} , Strides of the array is: {shape_strides[1]} ")

 Shape of the array is: (2, 4) , Strides of the array is: (16, 4) 


In [7]:
#11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements::

import numpy as np

In [45]:
def create_zeros_array(arr):
    n = int(input('Enter the no. of elements::'))
    arr = np.zeros(n)
    return arr
#Example
arr_zeros = create_zeros_array(arr)
print('A Numpy array of zeros is ::',arr_zeros)

Enter the no. of elements:: 4


A Numpy array of zeros is :: [0. 0. 0. 0.]


In [44]:
#12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D 
# NumPy array filled with ones of size `rows x cols`..
def create_ones_matrix(arr):
    rows = int(input('Enter no. of Rows::'))
    cols = int(input('Enter no. of columns::'))
    arr = np.ones((rows,cols))
    return arr
#Example
arr_ones = create_ones_matrix(arr)
print('A Numpy 2D-Array of ones is :',arr_ones)

Enter no. of Rows:: 5
Enter no. of columns:: 4


A Numpy 2D-Array of ones is : [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [46]:
#13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and 
# creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified 'step'::

def generate_range_array(arr):
    start = int(input('Enter the starting element'))
    stop = int(input('Enter the ending element'))
    step = int(input('Enter the step size'))
    arr = np.arange(start,stop,step)
    return arr
    
#Example
arr_with_step_size = generate_range_array(arr)
print(f"The Numpy array is :{arr_with_step_size}")

Enter the starting element 1
Enter the ending element 10
Enter the step size 1


The Numpy array is :[1 2 3 4 5 6 7 8 9]


In [48]:
#14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as 
# arguments and generates a NumPy array with num equally spaced values between `start` and `stop` inclusive).

def generate_linear_space(arr):
    start = float(input('Enter the starting element'))
    stop = float(input('Enter the ending element'))
    num = int(input('Enter the step size'))
    arr = np.linspace(start,stop,num)
    return arr
    
#Example
arr_linear_space = generate_linear_space(arr)
print(f"The Numpy array is :{arr_linear_space}")

Enter the starting element 2.2
Enter the ending element 7.9
Enter the step size 10


The Numpy array is :[2.2        2.83333333 3.46666667 4.1        4.73333333 5.36666667
 6.         6.63333333 7.26666667 7.9       ]


In [49]:
#15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square 
# identity matrix of size `n x n` using `numpy.eye`.
def create_identity_matrix(arr):
    n = int(input('Enter the no.::'))
    return np.eye(n)
#Example
array = create_identity_matrix(arr)
print('The squre identity matrix is::',array)

Enter the no.:: 4


The squre identity matrix is:: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [50]:
#16. Write a function that takes a Python list and converts it into a NumPy array:
def list_into_array(arr):
    list = []
    n = int(input('Enter the no.::'))
    for i in range(n):
        list.append(int(input("Enter the element")))
    return np.array(list)
#Example
array = list_into_array(arr)
print('The Numpy Array is ::',array)
    

Enter the no.:: 4
Enter the element 1
Enter the element 7
Enter the element 8
Enter the element 6


The Numpy Array is :: [1 7 8 6]


In [51]:
#17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data::

# Step 1: Create an initial NumPy array
original_array = np.array([9,8,3,6,1,4,2,4,5,8,7,9])
view_array = original_array.view()

#disply
print("Original array:", original_array)
print("View array:", view_array)

# Step 2: Modify the view array by reshape::
view_array = original_array.view().reshape(4,3)


# Display 
print("Modified view array:", view_array)

# again modify into 16 bit int ::
view_array_1 = original_array.view(np.int16)

#display
print("modified view array:",view_array_1)

Original array: [9 8 3 6 1 4 2 4 5 8 7 9]
View array: [9 8 3 6 1 4 2 4 5 8 7 9]
Modified view array: [[9 8 3]
 [6 1 4]
 [2 4 5]
 [8 7 9]]
modified view array: [9 0 8 0 3 0 6 0 1 0 4 0 2 0 4 0 5 0 8 0 7 0 9 0]


In [7]:
#18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

def concatenates_arrays(arr1,arr2,axis=0):
    return np.concatenate((arr1,arr2), axis=axis)

#Example
arr1 = np.array([[4,5,8],[5,9,7]])
arr2 = np.array([[5,9,3],[6,4,7]])
output_axis_0 = concatenates_arrays(arr1,arr2,axis=0)
print(output_axis_0)
output_axis_1 = concatenates_arrays(arr1,arr2,axis=1)
print(output_axis_1)

[[4 5 8]
 [5 9 7]
 [5 9 3]
 [6 4 7]]
[[4 5 8 5 9 3]
 [5 9 7 6 4 7]]


In [10]:
#19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy concatenate'::

arr1 = np.array([[4,6,7],[6,4,8]])
arr2 = np.array([[2,6],[8,7]])
result = np.concatenate((arr1,arr2), axis=1)
print(result)

[[4 6 7 2 6]
 [6 4 8 8 7]]


In [12]:
#20. Write a function that vertically stacks multiple NumPy arrays given as a list::

def vertically_stack(array):
    return np.vstack(array)

#Example
arr1 = [1,2,3]
arr2 = [4,5,6]
arr3 = [7,8,9]
result = vertically_stack([arr1,arr2,arr3])
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
#21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size::

def generate_range_array(arr):
    start = int(input('Enter the starting element'))
    stop = int(input('Enter the ending element'))
    step = int(input('Enter the step size'))
    arr = np.arange(start,stop+1,step)
    return arr
    
#Example
arr_with_step_size = generate_range_array(arr)
print(f"The Numpy array is :{arr_with_step_size}")


Enter the starting element 1
Enter the ending element 10
Enter the step size 1


The Numpy array is :[ 1  2  3  4  5  6  7  8  9 10]


In [21]:
#22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive)::

def generate_linear_space(start,stop,step):
    arr = np.linspace(start,stop,step)
    return arr
    
#Example
arr_linear_space = generate_linear_space(0,1,10)
print(f"The Numpy array is :{arr_linear_space}")


The Numpy array is :[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [30]:
#23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive)::

def generate_log_space(start,stop,step):
    arr = np.logspace(start,stop,step)
    return arr
    
#Example
arr_log_space = generate_log_space(0,3,5)
print(f"The Numpy array is :{arr_log_space}")


The Numpy array is :[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [36]:
#24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100::

import pandas as pd
  
array = np.random.randint(1,101, size=(5,3))
df = pd.DataFrame(array, columns=['Column_1', 'Column_2', 'Column_3'])
print(df)
    

    
  


   Column1  Column2  Column3
0       23       11       12
1       55        2       38
2       21       22        7
3       77       54       57
4        7      100       76


In [53]:
#25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame::

def negative_values_replace(df,column):
    df[column] = np.where(df[column]<0 , 0 , df[column])
    return df

#Example
data = {'A' : [5,2,-9,-8,6,-7,8],
      'B' : [-3,5,-9,6,8,-7,2]}
df= pd.DataFrame(data)
print(df)
df = negative_values_replace(df,'B')
print('After replacing negative values from the column::')
print(df)

   A  B
0  5 -3
1  2  5
2 -9 -9
3 -8  6
4  6  8
5 -7 -7
6  8  2
After replacing negative values from the column::
   A  B
0  5  0
1  2  5
2 -9  0
3 -8  6
4  6  8
5 -7  0
6  8  2


In [56]:
#26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2]
print(third_element)

30


In [66]:
#27. Retrieve the element at index (1, 2) from the 2D NumPy array::
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                   [7, 8, 9]])

element = arr_2d[1, 2]

print("The element at index (1, 2) is:", element)



The element at index (1, 2) is: 6


In [10]:
#28. Using boolean indexing, extract elements greater than 5 from the given NumPy array:

arr = np.array([3, 8, 2, 10, 5, 7])
greater_than_five = arr[arr > 5]
print(greater_than_five)

[ 8 10  7]


In [15]:
#29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array::

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
sliced_array = arr[2:6]
print(sliced_array)

[3 4 5 6]


In [24]:
#30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array::

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
sub_array = arr_2d[0:2 ,1:3]
print(sub_array)

[[2 3]
 [5 6]]


In [40]:
#31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array ::

def extract_from_2D_array(arr,indices):
    return np.take(arr,indices)

#Example
arr = np.array([[2,5,8],
               [6,5,3],
               [8,2,3]])
indices = np.array([[0,2] , [1,3]])

result =  extract_from_2D_array(arr,indices)
print(result)

[[2 8]
 [5 6]]


In [47]:
#32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing:::
def greater_than_threshold(arr,threshold):
    return arr[arr > threshold]

#Example
arr = np.array([2,5,3,10,47,59,2,3])
threshold = 7
result = greater_than_threshold(arr,threshold)
print(result)

[10 47 59]


In [15]:
#33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension::

def extracts_from_3d_array(arr, dim_1, dim_2, dim_3):
    first_result = np.take(arr, dim_1, axis = 0)
    next_result = np.take(first_result, dim_2, axis = 1)
    final_result = np.take(next_result, dim_2, axis = 2)
    return final_result

#Example
arr = np.arange(27).reshape(3,3,3)
dim_1 = [2,1,0]
dim_2 = [0,1,2]
dim_3 = [1,2,3]
extract_elements = extracts_from_3d_array(arr, dim_1, dim_2, dim_3)
print(extract_elements)
    

[[[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]]
